// test/utils/populateSquad.ts
import { PrismaClient } from '@prisma/client';

export async function populateSquad(prisma: PrismaClient) {
  await prisma.squad.deleteMany();

  await prisma.squad.createMany({
    data: [
      {
        name: 'Egil Selvik',
        position: 'Goalkeeper',
        squadNumber: 1,
        nationality: 'Norwegian',
        dateOfBirth: new Date('1997-07-30'),
        joinedDate: new Date('2025-01-01'),
        appearances: 19,
        goals: 0,
        assists: 0,
        startYear: 2025,
      },
      {
        name: 'Nathan Baxter',
        position: 'Goalkeeper',
        squadNumber: 12,
        nationality: 'British',
        dateOfBirth: new Date('1998-11-08'),
        joinedDate: new Date('2025-07-01'),
        appearances: 0,
        goals: 0,
        assists: 0,
        startYear: 2025,
      },
      {
        name: 'Alfie Marriot',
        position: 'Goalkeeper',
        squadNumber: 41,
        nationality: 'British',
        dateOfBirth: new Date('2004-03-26'),
        joinedDate: new Date('2019-01-01'),
        appearances: 0,
        goals: 0,
        assists: 0,
        startYear: 2019,
      },
      {
        name: 'Jeremy Ngakia',
        position: 'Defender',
        squadNumber: 2,
        nationality: 'British',
        dateOfBirth: new Date('2000-09-07'),
        joinedDate: new Date('2020-08-01'),
        appearances: 106,
        goals: 1,
        assists: 2,
        startYear: 2019,
      },
      {
        name: 'Ryan Andrews',
        position: 'Defender',
        squadNumber: 45,
        nationality: 'British',
        dateOfBirth: new Date('2004-08-26'),
        joinedDate: new Date('2023-01-01'),
        appearances: 94,
        goals: 6,
        assists: 5,
        startYear: 2020,
      },
      {
        name: 'Max Alleyne',
        position: 'Defender',
        squadNumber: 3,
        nationality: 'British',
        dateOfBirth: new Date('2005-07-21'),
        joinedDate: new Date('2025-08-01'),
        appearances: 0,
        goals: 0,
        assists: 0,
        startYear: 2025,
      },
      {
        name: 'Kevin Keben',
        position: 'Defender',
        squadNumber: 4,
        nationality: 'Cameroon',
        dateOfBirth: new Date('2004-01-26'),
        joinedDate: new Date('2024-08-01'),
        appearances: 9,
        goals: 0,
        assists: 0,
        startYear: 2024,
      },
      {
        name: 'Matthew Pollock',
        position: 'Defender',
        squadNumber: 6,
        nationality: 'British',
        dateOfBirth: new Date('2001-09-28'),
        joinedDate: new Date('2021-07-01'),
        appearances: 71,
        goals: 3,
        assists: 4,
        startYear: 2021,
      },
      {
        name: 'James Morris',
        position: 'Defender',
        squadNumber: 22,
        nationality: 'British',
        dateOfBirth: new Date('2001-11-23'),
        joinedDate: new Date('2021-09-01'),
        appearances: 52,
        goals: 0,
        assists: 0,
        startYear: 2021,
      },
      {
        name: 'James Abankwah',
        position: 'Defender',
        squadNumber: 25,
        nationality: 'Irish',
        dateOfBirth: new Date('2004-01-16'),
        joinedDate: new Date('2025-01-01'),
        appearances: 21,
        goals: 0,
        assists: 0,
        startYear: 2025,
      },
      {
        name: 'Marc Bola',
        position: 'Defender',
        squadNumber: 16,
        nationality: 'Irish',
        dateOfBirth: new Date('1997-12-09'),
        joinedDate: new Date('2025-07-01'),
        appearances: 3,
        goals: 0,
        assists: 0,
        startYear: 2025,
      },
      {
        name: 'Caleb Wiley',
        position: 'Defender',
        squadNumber: 26,
        nationality: 'United States',
        dateOfBirth: new Date('2004-12-22'),
        joinedDate: new Date('2025-02-01'),
        appearances: 10,
        goals: 0,
        assists: 1,
        startYear: 2025,
      },
      {
        name: 'Hector Kyprianou',
        position: 'Midfielder',
        squadNumber: 5,
        nationality: 'Cyprus',
        dateOfBirth: new Date('2001-05-27'),
        joinedDate: new Date('2025-07-01'),
        appearances: 3,
        goals: 0,
        assists: 0,
        startYear: 2025,
      },
      {
        name: 'Imran Louza',
        position: 'Midfielder',
        squadNumber: 10,
        nationality: 'Morocco',
        dateOfBirth: new Date('1999-05-01'),
        joinedDate: new Date('2021-07-01'),
        appearances: 100,
        goals: 8,
        assists: 14,
        startYear: 2021,
      },
      {
        name: 'Pierre Dwomoh',
        position: 'Midfielder',
        squadNumber: 14,
        nationality: 'Belgium',
        dateOfBirth: new Date('2004-07-21'),
        joinedDate: new Date('2024-08-01'),
        appearances: 11,
        goals: 0,
        assists: 0,
        startYear: 2024,
      },
      {
        name: 'Tom Dele-Bashiru',
        position: 'Midfielder',
        squadNumber: 24,
        nationality: 'Nigeria',
        dateOfBirth: new Date('1999-09-17'),
        joinedDate: new Date('2019-07-01'),
        appearances: 76,
        goals: 8,
        assists: 4,
        startYear: 2019,
      },
      {
        name: 'Moussa Sissoko',
        position: 'Midfielder',
        squadNumber: 17,
        nationality: 'France',
        dateOfBirth: new Date('1989-08-16'),
        joinedDate: new Date('2024-07-01'),
        appearances: 76,
        goals: 8,
        assists: 2,
        startYear: 2024,
      },
      {
        name: 'Thomas Ince',
        position: 'Midfielder',
        squadNumber: 7,
        nationality: 'British',
        dateOfBirth: new Date('1992-01-30'),
        joinedDate: new Date('2023-07-01'),
        appearances: 67,
        goals: 7,
        assists: 4,
        startYear: 2024,
      },
      {
        name: 'Edo Kayembe',
        position: 'Midfielder',
        squadNumber: 39,
        nationality: 'DR Congo',
        dateOfBirth: new Date('1998-07-03'),
        joinedDate: new Date('2022-01-01'),
        appearances: 67,
        goals: 13,
        assists: 3,
        startYear: 2022,
      },
      {
        name: 'Othmane Maamma',
        position: 'Forward',
        squadNumber: 42,
        nationality: 'DR Congo',
        dateOfBirth: new Date('2005-10-06'),
        joinedDate: new Date('2025-07-01'),
        appearances: 0,
        goals: 0,
        assists: 0,
        startYear: 2025,
      },
      {
        name: 'Kwadwo Baah',
        position: 'Forward',
        squadNumber: 34,
        nationality: 'British',
        dateOfBirth: new Date('2003-01-27'),
        joinedDate: new Date('2021-07-01'),
        appearances: 34,
        goals: 6,
        assists: 3,
        startYear: 2021,
      },
      {
        name: 'Giorgi Chakvetadze',
        position: 'Midfielder',
        squadNumber: 10,
        nationality: 'Georgian',
        dateOfBirth: new Date('1999-08-29'),
        joinedDate: new Date('2023-08-01'),
        appearances: 25,
        goals: 4,
        assists: 6,
        startYear: 2023,
      },
      {
        name: 'Rocco Vata',
        position: 'Forward',
        squadNumber: 11,
        nationality: 'Irish',
        dateOfBirth: new Date('2005-04-18'),
        joinedDate: new Date('2024-07-01'),
        appearances: 37,
        goals: 4,
        assists: 4,
        startYear: 2024,
      },
      {
        name: 'Luca Kjerrumgaard',
        position: 'Forward',
        squadNumber: 9,
        nationality: 'Denmark',
        dateOfBirth: new Date('2003-02-09'),
        joinedDate: new Date('2025-07-01'),
        appearances: 3,
        goals: 2,
        assists: 0,
        startYear: 2025,
      },
      {
        name: 'Vivaldo Semedo',
        position: 'Forward',
        squadNumber: 18,
        nationality: 'Portugal',
        dateOfBirth: new Date('2005-01-28'),
        joinedDate: new Date('2025-07-01'),
        appearances: 1,
        goals: 0,
        assists: 0,
        startYear: 2025,
      },
      {
        name: 'Mamadou Doumbia',
        position: 'Forward',
        squadNumber: 20,
        nationality: 'Mali',
        dateOfBirth: new Date('2006-02-18'),
        joinedDate: new Date('2024-07-01'),
        appearances: 24,
        goals: 2,
        assists: 0,
        startYear: 2024,
      },
      {
        name: 'Nesteroy Irankunda',
        position: 'Forward',
        squadNumber: 66,
        nationality: 'Australia',
        dateOfBirth: new Date('2006-02-09'),
        joinedDate: new Date('2025-07-01'),
        appearances: 3,
        goals: 0,
        assists: 2,
        startYear: 2025,
      },
    ],
  });
}
